application: pigeon-farm
version: 1
runtime: python
api_version: 1

handlers:
- url: /inbound/
  script: inbound.py
  secure: always

- url: /tasks/.*
  script: tasks.py
  login: admin

- url: .*
  script: main.py
  login: admin
  secure: always
